# Generated by Django 5.2 on 2025-04-17 18:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administrativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=12, unique=True)),
                ('nombre', models.CharField(max_length=200)),
                ('apellidos', models.CharField(max_length=200)),
                ('usuario', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('clave', models.CharField(max_length=128)),
                ('fechaNacimiento', models.DateField()),
                ('direccion', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'E11EVENSTORE_ADMINISTRATIVOS',
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('rut', models.CharField(max_length=12, primary_key=True, serialize=False, verbose_name='RUT')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombres')),
                ('apellidos', models.CharField(max_length=200, verbose_name='Apellidos')),
                ('usuario', models.CharField(max_length=150, verbose_name='Nombre Usuario')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Correo electrónico')),
                ('clave', models.CharField(max_length=128, verbose_name='Contraseña')),
                ('fechaNacimiento', models.DateField(verbose_name='Fecha de nacimiento')),
                ('direccion', models.CharField(blank=True, max_length=255, null=True, verbose_name='Dirección')),
            ],
            options={
                'db_table': 'E11EVENSTORE_CLIENTES',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('precio', models.PositiveIntegerField()),
                ('categoria', models.CharField(choices=[('CAT_1', 'Carreras'), ('CAT_2', 'Terror'), ('CAT_3', 'Mundo abierto'), ('CAT_4', 'Free to play'), ('CAT_5', 'Acción'), ('CAT_6', 'Supervivencia')], max_length=20)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='productos/')),
                ('stock', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_compra', models.CharField(max_length=20, unique=True, verbose_name='Número de compra')),
                ('direccion_envio', models.CharField(max_length=255, verbose_name='Dirección de envío')),
                ('metodo_pago', models.CharField(max_length=50, verbose_name='Método de pago')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de compra')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('enviado', 'Enviado')], default='pendiente', max_length=20, verbose_name='Estado de compra')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compras', to='E11evenStore.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('compra', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='E11evenStore.compra')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='E11evenStore.producto')),
            ],
        ),
    ]
