# Generated by Django 5.2 on 2025-04-17 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('E11evenStore', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(default=1, upload_to='productos/'),
            preserve_default=False,
        ),
    ]
