# Generated by Django 5.2 on 2025-04-17 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('E11evenStore', '0002_alter_producto_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.CharField(choices=[('CAT_1', 'Carreras'), ('CAT_2', 'Terror'), ('CAT_3', 'Mundo abierto'), ('CAT_4', 'Free to play'), ('CAT_5', 'Accion'), ('CAT_6', 'Supervivencia')], max_length=20),
        ),
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.URLField(),
        ),
    ]
