# Generated by Django 5.2 on 2025-04-19 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("E11evenStore", "0004_alter_producto_descripcion"),
    ]

    operations = [
        migrations.AlterField(
            model_name="producto",
            name="categoria",
            field=models.CharField(
                choices=[
                    ("CAT_1-Carreras", "Carreras"),
                    ("CAT_2-Terror", "Terror"),
                    ("CAT_3-Mundo abierto", "Mundo abierto"),
                    ("CAT_4-Free to play", "Free to play"),
                    ("CAT_5-Accion", "Acción"),
                    ("CAT_6-Supervivencia", "Supervivencia"),
                ],
                max_length=50,
            ),
        ),
    ]
