# Generated by Django 5.2 on 2025-04-19 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("E11evenStore", "0006_alter_producto_imagen_customuser_producto_creado_por"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="producto",
            name="creado_por",
        ),
        migrations.AlterField(
            model_name="producto",
            name="imagen",
            field=models.URLField(),
        ),
        migrations.DeleteModel(
            name="CustomUser",
        ),
    ]
