# Generated by Django 5.2 on 2025-04-19 22:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "E11evenStore",
            "0007_remove_producto_creado_por_alter_producto_imagen_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="TransaccionPago",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "metodo_pago",
                    models.CharField(
                        choices=[
                            ("giftcard", "GiftCard"),
                            ("debito", "Débito"),
                            ("credito", "Crédito"),
                            ("transferencia", "Transferencia Bancaria"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("pendiente", "Pendiente"),
                            ("completado", "Completado"),
                            ("fallido", "Fallido"),
                        ],
                        default="pendiente",
                        max_length=15,
                    ),
                ),
                ("monto", models.DecimalField(decimal_places=2, max_digits=10)),
                ("fecha_transaccion", models.DateTimeField(auto_now_add=True)),
                (
                    "codigo_autorizacion",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "compra",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transacciones",
                        to="E11evenStore.compra",
                    ),
                ),
            ],
        ),
    ]
