# Generated by Django 5.2 on 2025-04-30 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("E11evenStore", "0009_alter_cliente_usuario"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cliente",
            name="usuario",
            field=models.CharField(
                blank=True, max_length=150, unique=True, verbose_name="Nombre Usuario"
            ),
        ),
    ]
